//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeetSpeek
    {
        public System.Guid Id { get; set; }
        public string InputText { get; set; }
        public string TranslatedText { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string TranslationType { get; set; }
    }
}
